#!/bin/bash

#Set no of days
days=4

#Get the current data in seconds
current=$(date +%s)

#loop through all files in the current directory
for file in *
do
        #check if the fike is older than x days
        if [ -f "$file" ] && [ $(($current - $(date +%s -r "$file"))) -gt $(($days * 24 * 60 * 60)) ];
        then
                #remove the file
                rm "$file"
                echo "$file deleted"

        fi
done
