#!/bin/bash
#digital clock

#define colors
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
NC="\033[0m"


while true;
do
        clear
echo "  🕒 Digital Clock     "
echo "========================"
echo -e "Time : ${YELLOW}$(date +"%H:%M:%S")${NC}"
echo -e "Date : ${CYAN}$(date +"%d-%m-%y")${NC}"
sleep 1
done
