#!/bin/bash

#simple password generator

echo "Welcome to simple password genertor"

sleep 1

echo "Please Enter the length of the password"
read PASS_LENGTH

for p in $(seq 1 );
do
        openssl rand -hex 16 | cut -c1-$PASS_LENGTH
done
